import {
    addDishesToCart,
    getPayments,
    getRestaurantMenu,
    getRestaurants,
    getUser,
    getUserAddress,
    getUserAuthenticationCode,
    loginUser,
    setAddressInOrder,
    setPaymentInOrder,
    submitOrder,
} from './core'
export default {
    addDishesToCart,
    getPayments,
    getRestaurantMenu,
    getRestaurants,
    getUser,
    getUserAddress,
    getUserAuthenticationCode,
    loginUser,
    setAddressInOrder,
    setPaymentInOrder,
    submitOrder,
}
