import {
    addDishesToCart,
    getPayments,
    getRestaurantMenu,
    getRestaurants,
    getUser,
    getAuthToken,
    getUserAddress,
    getUserAuthenticationCode,
    loginUser,
    setAddressInOrder,
    setPaymentInOrder,
    submitOrder,
    loadTenbisCredit,
    getTransactionReport,
} from './core'

export default {
    addDishesToCart,
    getPayments,
    getRestaurantMenu,
    getRestaurants,
    getUser,
    getUserAddress,
    getAuthToken,
    getUserAuthenticationCode,
    loginUser,
    setAddressInOrder,
    setPaymentInOrder,
    submitOrder,
    loadTenbisCredit,
    getTransactionReport,
}
